version: '3'
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: draw-menu
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  draw-menu:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
        - DB_NAME=draw-menu
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_HOST=postgres_db
        - DB_PORT=5432

    volumes:
      - ./service:/service
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db