# Generated by Django 4.2 on 2024-03-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Url')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child', to='app.menu', verbose_name='Родитель')),
            ],
        ),
    ]
